// Add accepted or published papers here once; the homepage and CV render from this list.
// Set peerReviewed: false for items that should not appear under CV peer-reviewed publications.
window.PUBLICATIONS = [
  {
    year: "2026",
    title: "AI-Driven MetaHuman for Immersive VR Property Tours: Design and Early Evaluation",
    authors: ["Talukder, M. G. M.", "Iqbal, M. Z.", "Akinade, O."],
    myAuthorName: "Talukder, M. G. M.",
    type: "Conference Paper",
    venue: "ACM Proceedings",
    cvVenue: "Proceedings of the 2026 ACM International Conference on Interactive Media Experiences (IMX '26)",
    details: "548-552. Work-in-Progress paper.",
    doi: "10.1145/3788851.3815040",
    peerReviewed: true,
    selected: true,
  },
  {
    year: "2026",
    title: "Machine Learning-Based Diabetes Risk Prediction via DiaHealth Dataset with Explainable AI and Streamlit Deployment",
    authors: ["Adeyemi, S.", "Iqbal, M. Z.", "Talukder, M. G. M."],
    myAuthorName: "Talukder, M. G. M.",
    type: "Journal Article",
    venue: "Future Internet",
    cvVenue: "Future Internet",
    details: "18(6), 331.",
    doi: "10.3390/fi18060331",
    peerReviewed: true,
    selected: true,
  },
  {
    year: "2025",
    title: "Exploring the Nexus: A Systematic Literature Review on Meta-Influencers in Immersive Brand Engagement",
    authors: ["Talukder, M. G. M.", "Akinade, O.", "Iqbal, M. Z."],
    myAuthorName: "Talukder, M. G. M.",
    type: "Journal Article",
    venue: "Metaverse",
    cvVenue: "Metaverse",
    details: "6(4), Article 8225.",
    doi: "10.54517/m8225",
    peerReviewed: true,
    selected: true,
  },
  {
    year: "2025",
    title: "Data-Driven Predictive Modelling of Lifestyle Risk Factors for Cardiovascular Health",
    authors: ["Kissi, S. A.", "Talukder, M. G. M.", "Iqbal, M. Z."],
    myAuthorName: "Talukder, M. G. M.",
    type: "Journal Article",
    venue: "Electronics",
    cvVenue: "Electronics",
    details: "14(14), 2906.",
    doi: "10.3390/electronics14142906",
    peerReviewed: true,
    selected: true,
  },
  {
    year: "2023",
    title: "Identifying the Role of Digital Marketing in Changing Consumers' Buying Decision",
    authors: ["Talukder, M. G. M."],
    myAuthorName: "Talukder, M. G. M.",
    type: "MSc Dissertation",
    venue: "University of South-Eastern Norway",
    cvVenue: "University of South-Eastern Norway",
    details: "",
    doi: "10.13140/RG.2.2.32545.47204",
    peerReviewed: false,
    selected: true,
  },
];
